import { StyleSheet } from "react-native";

import Colors from "./Colors";
import * as SPACING from "./spacing";
import * as TYPOGRAPHY from "./typography";

export const globalStyles = StyleSheet.create({
  bgColorTransparent: {
    backgroundColor: Colors.transparent,
  },
  safeArea: {
    height: "100%",
    width: "100%",
    backgroundColor: Colors.darkDark1,
  },
  header: {
    paddingHorizontal: SPACING.SCALE_24,
    display: "flex",
    flexDirection: "column",
    gap: SPACING.SCALE_24,
  },
  container: {
    display: "flex",
    paddingHorizontal: SPACING.SCALE_24,
    flexDirection: "column",
    gap: SPACING.SCALE_24,
  },
  footer: {
    display: "flex",
    width: "100%",
    padding: SPACING.SCALE_24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: SPACING.SCALE_1,
    borderTopColor: Colors.darkDark5,
  },
  footerButton: {
    padding: SPACING.SCALE_16,
    width: "100%",
  },
  footerButton2: {
    padding: SPACING.SCALE_16,
    width: "48%",
  },
  center: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  textMiniSemiBold: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistSemiBold,
    fontSize: TYPOGRAPHY.FONT_SIZE_12,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_SEMI_BOLD,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_19_2,
  },
  textMiniBold: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistBold,
    fontSize: TYPOGRAPHY.FONT_SIZE_12,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_BOLD,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_19_2,
  },
  inputMiniBold: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistBold,
    fontSize: TYPOGRAPHY.FONT_SIZE_12,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_BOLD,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_19_2,
  },
  textMiniSemiRegular: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.Urbanist,
    fontSize: TYPOGRAPHY.FONT_SIZE_12,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_REGULAR,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_19_2,
  },
  textMini2SemiRegular: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistRegular,
    fontSize: TYPOGRAPHY.FONT_SIZE_14,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_REGULAR,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_22_4,
  },
  textMini2Bold: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistBold,
    fontSize: TYPOGRAPHY.FONT_SIZE_14,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_BOLD,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_22_4,
  },
  inputMini2Bold: {
    fontFamily: TYPOGRAPHY.UrbanistBold,
    fontSize: TYPOGRAPHY.FONT_SIZE_14,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_BOLD,
  },
  textMini2SemiMedium: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistMedium,
    fontSize: TYPOGRAPHY.FONT_SIZE_14,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_MEDIUM,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_22_4,
  },
  textSmallThin: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistThin,
    fontSize: TYPOGRAPHY.FONT_SIZE_16,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_THIN,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_25_6,
  },
  textSmallRegular: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistRegular,
    fontSize: TYPOGRAPHY.FONT_SIZE_16,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_REGULAR,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_25_6,
  },
  textSmallMedium: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistMedium,
    fontSize: TYPOGRAPHY.FONT_SIZE_16,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_MEDIUM,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_25_6,
  },
  textSmallSemiBold: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistSemiBold,
    fontSize: TYPOGRAPHY.FONT_SIZE_16,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_SEMI_BOLD,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_26,
  },
  textSmallBold: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistBold,
    fontSize: TYPOGRAPHY.FONT_SIZE_16,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_BOLD,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_26,
  },
  textMediumRegular: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistRegular,
    fontSize: TYPOGRAPHY.FONT_SIZE_18,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_REGULAR,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_29,
  },
  inputMediumRegular: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistRegular,
    fontSize: TYPOGRAPHY.FONT_SIZE_18,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_REGULAR,
  },
  textMediumThin: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistThin,
    fontSize: TYPOGRAPHY.FONT_SIZE_18,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_THIN,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_29,
  },
  textMediumMedium: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistMedium,
    fontSize: TYPOGRAPHY.FONT_SIZE_18,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_MEDIUM,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_29,
  },
  textMediumSemiBold: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistSemiBold,
    fontSize: TYPOGRAPHY.FONT_SIZE_18,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_SEMI_BOLD,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_29,
  },
  textMediumBold: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistBold,
    fontSize: TYPOGRAPHY.FONT_SIZE_18,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_BOLD,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_29,
  },
  inputMediumBold: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistBold,
    fontSize: TYPOGRAPHY.FONT_SIZE_18,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_BOLD,
  },
  textLargeMedium: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistMedium,
    fontSize: TYPOGRAPHY.FONT_SIZE_20,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_MEDIUM,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_32,
  },
  textLargeSemiBold: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistSemiBold,
    fontSize: TYPOGRAPHY.FONT_SIZE_20,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_SEMI_BOLD,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_32,
  },
  textLargeBold: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistBold,
    fontSize: TYPOGRAPHY.FONT_SIZE_20,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_BOLD,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_32,
  },
  inputLargeBold: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistBold,
    fontSize: TYPOGRAPHY.FONT_SIZE_20,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_BOLD,
  },
  textExtraSemiBold: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistSemiBold,
    fontSize: TYPOGRAPHY.FONT_SIZE_24,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_SEMI_BOLD,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_38_5,
  },
  textExtraBold: {
    alignSelf: "stretch",
    fontFamily: TYPOGRAPHY.UrbanistBold,
    fontSize: TYPOGRAPHY.FONT_SIZE_24,
    fontWeight: TYPOGRAPHY.FONT_WEIGHT_BOLD,
    lineHeight: TYPOGRAPHY.LINE_HEIGHT_38_5,
  },
});
