export const API = {
    POST: "post",
    GET: "get",
    PUT: "put",
    BASE_URL: process.env.EXPO_PUBLIC_BASE_URL,
    LIMIT: 10,

    API_GET_DOCTORS: '/doctors',
    LOGIN_GOOGLE: '/auth/login-google',
    API_GET_USER: '/users/profile',
    API_GET_SPECIALIZATIONS: '/specializations',
    API_BASE_FEEDBACK: '/feedbacks',
    API_GET_COUNT_PATIENT_BY_DOCTOR: '/doctors/count-patients',
    API_GET_TIMEWORKING: '/doctors/get-timeworking',
    API_BASE_PATIENT: '/patients',
    API_GET_APPOINTMENT_BY_USERID: '/appointments/get-by-user',
    API_BASE_GET_PACKAGE_APPOINTMENT: '/package-appointments',
    API_GET_DOCTORS_FAVORITE: '/patients/get-doctor-favorite',
    API_GET_DOCTORS_BY_SPECIALITY: '/doctors/speciality',
    API_GET_DOCTORS_TOP: '/doctor/get-doctor-favorite',
    API_FAVORITE_DOCTOR: '/patients/favorite-doctor',
    API_LOGIN_PASSWORD: '/auth/login',
    API_SINGUP_PASSWORD: '/auth/signup',
    API_VERIFY_CODE: '/auth/verify-email',
    API_GET_TOKEN_STREAMCHAT: '/users/token-stream-chat',
    API_CANCEL_APPOINTMENT: '/appointments/cancel',
    API_COMPLETE_APPOINTMENT: '/appointments/complete',
    API_BASE_DOCTOR: '/doctors',
    API_PATIENT_FEEDBACK: '/patients/feedback/create',
    API_GET_FEEDBACK_APPOINTMENT: '/feedbacks/appointment',
    API_UPDATE_FEEDBACK: '/patients/feedback/update',
}